/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== Makefile.am ==================
static const unsigned char temp_binary_data_0[] =
"## Process this file with automake to create Makefile.in\n"
"##\n"
"## This file is part of SoundTouch, an audio processing library for pitch/time adjustments\n"
"##\n"
"## SoundTouch is free software; you can redistribute it and/or modify it under the\n"
"## terms of the GNU General Public License as published by the Free Software\n"
"## Foundation; either version 2 of the License, or (at your option) any later\n"
"## version.\n"
"##\n"
"## SoundTouch is distributed in the hope that it will be useful, but WITHOUT ANY\n"
"## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR\n"
"## A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n"
"##\n"
"## You should have received a copy of the GNU General Public License along with\n"
"## this program; if not, write to the Free Software Foundation, Inc., 59 Temple\n"
"## Place - Suite 330, Boston, MA  02111-1307, USA\n"
"\n"
"\n"
"include $(top_srcdir)/config/am_include.mk\n"
"\n"
"\n"
"# set to something if you want other stuff to be included in the distribution tarball\n"
"EXTRA_DIST=SoundTouch.sln SoundTouch.vcxproj\n"
"\n"
"noinst_HEADERS=AAFilter.h cpu_detect.h cpu_detect_x86.cpp FIRFilter.h RateTransposer.h TDStretch.h PeakFinder.h \\\n"
"    InterpolateCubic.h InterpolateLinear.h InterpolateShannon.h\n"
"\n"
"lib_LTLIBRARIES=libSoundTouch.la\n"
"#\n"
"libSoundTouch_la_SOURCES=AAFilter.cpp FIRFilter.cpp FIFOSampleBuffer.cpp    \\\n"
"    RateTransposer.cpp SoundTouch.cpp TDStretch.cpp cpu_detect_x86.cpp      \\\n"
"    BPMDetect.cpp PeakFinder.cpp InterpolateLinear.cpp InterpolateCubic.cpp \\\n"
"    InterpolateShannon.cpp\n"
"\n"
"# Compiler flags\n"
"#AM_CXXFLAGS+=\n"
"\n"
"# Compile the files that need MMX and SSE individually.\n"
"libSoundTouch_la_LIBADD=libSoundTouchMMX.la libSoundTouchSSE.la\n"
"noinst_LTLIBRARIES=libSoundTouchMMX.la libSoundTouchSSE.la\n"
"libSoundTouchMMX_la_SOURCES=mmx_optimized.cpp\n"
"libSoundTouchSSE_la_SOURCES=sse_optimized.cpp\n"
"\n"
"# We enable optimizations by default.\n"
"# If MMX is supported compile with -mmmx.\n"
"# Do not assume -msse is also supported.\n"
"if HAVE_MMX\n"
"libSoundTouchMMX_la_CXXFLAGS = -mmmx $(AM_CXXFLAGS)\n"
"else\n"
"libSoundTouchMMX_la_CXXFLAGS = $(AM_CXXFLAGS)\n"
"endif\n"
"\n"
"# We enable optimizations by default.\n"
"# If SSE is supported compile with -msse.\n"
"if HAVE_SSE\n"
"libSoundTouchSSE_la_CXXFLAGS = -msse $(AM_CXXFLAGS)\n"
"else\n"
"libSoundTouchSSE_la_CXXFLAGS = $(AM_CXXFLAGS)\n"
"endif\n"
"\n"
"# Let the user disable optimizations if he wishes to.\n"
"if !X86_OPTIMIZATIONS\n"
"libSoundTouchMMX_la_CXXFLAGS = $(AM_CXXFLAGS)\n"
"libSoundTouchSSE_la_CXXFLAGS = $(AM_CXXFLAGS)\n"
"endif\n"
"\n"
"# Modify the default 0.0.0 to LIB_SONAME.0.0\n"
"libSoundTouch_la_LDFLAGS=-version-info @LIB_SONAME@\n"
"\n"
"# other linking flags to add\n"
"# noinst_LTLIBRARIES = libSoundTouchOpt.la\n"
"# libSoundTouch_la_LIBADD = libSoundTouchOpt.la\n"
"# libSoundTouchOpt_la_SOURCES = mmx_optimized.cpp sse_optimized.cpp\n"
"# libSoundTouchOpt_la_CXXFLAGS = -O3 -msse -fcheck-new -I../../include\n";

const char* Makefile_am = (const char*) temp_binary_data_0;

//================== SoundTouch.sln ==================
static const unsigned char temp_binary_data_1[] =
"Microsoft Visual Studio Solution File, Format Version 12.00\r\n"
"# Visual Studio 14\r\n"
"VisualStudioVersion = 14.0.23107.0\r\n"
"MinimumVisualStudioVersion = 10.0.40219.1\r\n"
"Project(\"{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}\") = \"SoundTouch\", \"SoundTouch.vcxproj\", \"{68A5DD20-7057-448B-8FE0-B6AC8D205509}\"\r\n"
"EndProject\r\n"
"Global\r\n"
"\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\r\n"
"\t\tDebug|Win32 = Debug|Win32\r\n"
"\t\tDebug|x64 = Debug|x64\r\n"
"\t\tRelease|Win32 = Release|Win32\r\n"
"\t\tRelease|x64 = Release|x64\r\n"
"\t\tReleaseX64|Win32 = ReleaseX64|Win32\r\n"
"\t\tReleaseX64|x64 = ReleaseX64|x64\r\n"
"\tEndGlobalSection\r\n"
"\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\r\n"
"\t\t{68A5DD20-7057-448B-8FE0-B6AC8D205509}.Debug|Win32.ActiveCfg = Debug|Win32\r\n"
"\t\t{68A5DD20-7057-448B-8FE0-B6AC8D205509}.Debug|x64.ActiveCfg = Debug|x64\r\n"
"\t\t{68A5DD20-7057-448B-8FE0-B6AC8D205509}.Release|Win32.ActiveCfg = Release|Win32\r\n"
"\t\t{68A5DD20-7057-448B-8FE0-B6AC8D205509}.Release|x64.ActiveCfg = Release|x64\r\n"
"\t\t{68A5DD20-7057-448B-8FE0-B6AC8D205509}.ReleaseX64|Win32.ActiveCfg = ReleaseX64|Win32\r\n"
"\t\t{68A5DD20-7057-448B-8FE0-B6AC8D205509}.ReleaseX64|Win32.Build.0 = ReleaseX64|Win32\r\n"
"\t\t{68A5DD20-7057-448B-8FE0-B6AC8D205509}.ReleaseX64|x64.ActiveCfg = ReleaseX64|x64\r\n"
"\t\t{68A5DD20-7057-448B-8FE0-B6AC8D205509}.ReleaseX64|x64.Build.0 = ReleaseX64|x64\r\n"
"\tEndGlobalSection\r\n"
"\tGlobalSection(SolutionProperties) = preSolution\r\n"
"\t\tHideSolutionNode = FALSE\r\n"
"\tEndGlobalSection\r\n"
"EndGlobal\r\n";

const char* SoundTouch_sln = (const char*) temp_binary_data_1;

//================== SoundTouch.vcxproj ==================
static const unsigned char temp_binary_data_2[] =
"\xef\xbb\xbf<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
"<Project DefaultTargets=\"Build\" ToolsVersion=\"14.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\r\n"
"  <ItemGroup Label=\"ProjectConfigurations\">\r\n"
"    <ProjectConfiguration Include=\"Debug|Win32\">\r\n"
"      <Configuration>Debug</Configuration>\r\n"
"      <Platform>Win32</Platform>\r\n"
"    </ProjectConfiguration>\r\n"
"    <ProjectConfiguration Include=\"Debug|x64\">\r\n"
"      <Configuration>Debug</Configuration>\r\n"
"      <Platform>x64</Platform>\r\n"
"    </ProjectConfiguration>\r\n"
"    <ProjectConfiguration Include=\"Release|Win32\">\r\n"
"      <Configuration>Release</Configuration>\r\n"
"      <Platform>Win32</Platform>\r\n"
"    </ProjectConfiguration>\r\n"
"    <ProjectConfiguration Include=\"Release|x64\">\r\n"
"      <Configuration>Release</Configuration>\r\n"
"      <Platform>x64</Platform>\r\n"
"    </ProjectConfiguration>\r\n"
"  </ItemGroup>\r\n"
"  <PropertyGroup Label=\"Globals\">\r\n"
"    <ProjectGuid>{68A5DD20-7057-448B-8FE0-B6AC8D205509}</ProjectGuid>\r\n"
"    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>\r\n"
"  </PropertyGroup>\r\n"
"  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\" />\r\n"
"  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\" Label=\"Configuration\">\r\n"
"    <ConfigurationType>StaticLibrary</ConfigurationType>\r\n"
"    <PlatformToolset>v143</PlatformToolset>\r\n"
"    <UseOfMfc>false</UseOfMfc>\r\n"
"    <CharacterSet>Unicode</CharacterSet>\r\n"
"  </PropertyGroup>\r\n"
"  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\" Label=\"Configuration\">\r\n"
"    <ConfigurationType>StaticLibrary</ConfigurationType>\r\n"
"    <PlatformToolset>v143</PlatformToolset>\r\n"
"    <UseOfMfc>false</UseOfMfc>\r\n"
"    <CharacterSet>Unicode</CharacterSet>\r\n"
"  </PropertyGroup>\r\n"
"  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\" Label=\"Configuration\">\r\n"
"    <ConfigurationType>StaticLibrary</ConfigurationType>\r\n"
"    <PlatformToolset>v143</PlatformToolset>\r\n"
"    <UseOfMfc>false</UseOfMfc>\r\n"
"    <CharacterSet>Unicode</CharacterSet>\r\n"
"  </PropertyGroup>\r\n"
"  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\" Label=\"Configuration\">\r\n"
"    <ConfigurationType>StaticLibrary</ConfigurationType>\r\n"
"    <PlatformToolset>v143</PlatformToolset>\r\n"
"    <UseOfMfc>false</UseOfMfc>\r\n"
"    <CharacterSet>Unicode</CharacterSet>\r\n"
"  </PropertyGroup>\r\n"
"  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.props\" />\r\n"
"  <ImportGroup Label=\"ExtensionSettings\">\r\n"
"  </ImportGroup>\r\n"
"  <ImportGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\" Label=\"PropertySheets\">\r\n"
"    <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\r\n"
"    <Import Project=\"$(VCTargetsPath)Microsoft.CPP.UpgradeFromVC71.props\" />\r\n"
"  </ImportGroup>\r\n"
"  <ImportGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\" Label=\"PropertySheets\">\r\n"
"    <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\r\n"
"    <Import Project=\"$(VCTargetsPath)Microsoft.CPP.UpgradeFromVC71.props\" />\r\n"
"  </ImportGroup>\r\n"
"  <ImportGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\" Label=\"PropertySheets\">\r\n"
"    <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\r\n"
"    <Import Project=\"$(VCTargetsPath)Microsoft.CPP.UpgradeFromVC71.props\" />\r\n"
"  </ImportGroup>\r\n"
"  <ImportGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\" Label=\"PropertySheets\">\r\n"
"    <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\r\n"
"    <Import Project=\"$(VCTargetsPath)Microsoft.CPP.UpgradeFromVC71.props\" />\r\n"
"  </ImportGroup>\r\n"
"  <PropertyGroup Label=\"UserMacros\" />\r\n"
"  <PropertyGroup>\r\n"
"    <_ProjectFileVersion>14.0.23107.0</_ProjectFileVersion>\r\n"
"  </PropertyGroup>\r\n"
"  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">\r\n"
"    <OutDir>$(Platform)\\$(Configuration)\\</OutDir>\r\n"
"    <IntDir>$(Platform)\\$(Configuration)\\</IntDir>\r\n"
"  </PropertyGroup>\r\n"
"  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">\r\n"
"    <OutDir>$(Platform)\\$(Configuration)\\</OutDir>\r\n"
"    <IntDir>$(Platform)\\$(Configuration)\\</IntDir>\r\n"
"    <TargetName>$(ProjectName)_x64</TargetName>\r\n"
"  </PropertyGroup>\r\n"
"  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">\r\n"
"    <OutDir>$(Platform)\\$(Configuration)\\</OutDir>\r\n"
"    <IntDir>$(Platform)\\$(Configuration)\\</IntDir>\r\n"
"    <TargetName>$(ProjectName)D</TargetName>\r\n"
"  </PropertyGroup>\r\n"
"  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">\r\n"
"    <OutDir>$(Platform)\\$(Configuration)\\</OutDir>\r\n"
"    <IntDir>$(Platform)\\$(Configuration)\\</IntDir>\r\n"
"    <TargetName>$(ProjectName)D_x64</TargetName>\r\n"
"  </PropertyGroup>\r\n"
"  <ItemDefinitionGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">\r\n"
"    <ClCompile>\r\n"
"      <Optimization>Full</Optimization>\r\n"
"      <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>\r\n"
"      <IntrinsicFunctions>true</IntrinsicFunctions>\r\n"
"      <AdditionalIncludeDirectories>..\\..\\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>\r\n"
"      <PreprocessorDefinitions>WIN32;NDEBUG;_LIB;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n"
"      <StringPooling>true</StringPooling>\r\n"
"      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>\r\n"
"      <FunctionLevelLinking>true</FunctionLevelLinking>\r\n"
"      <FloatingPointModel>Fast</FloatingPointModel>\r\n"
"      <PrecompiledHeader />\r\n"
"      <PrecompiledHeaderOutputFile>$(OutDir)$(TargetName).pch</PrecompiledHeaderOutputFile>\r\n"
"      <AssemblerListingLocation>$(OutDir)</AssemblerListingLocation>\r\n"
"      <ObjectFileName>$(OutDir)</ObjectFileName>\r\n"
"      <ProgramDataBaseFileName>$(OutDir)</ProgramDataBaseFileName>\r\n"
"      <WarningLevel>Level3</WarningLevel>\r\n"
"      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n"
"      <DebugInformationFormat />\r\n"
"      <CompileAs>Default</CompileAs>\r\n"
"      <EnableEnhancedInstructionSet>StreamingSIMDExtensions2</EnableEnhancedInstructionSet>\r\n"
"      <XMLDocumentationFileName>$(IntDir)</XMLDocumentationFileName>\r\n"
"      <BrowseInformationFile>$(IntDir)</BrowseInformationFile>\r\n"
"      <MultiProcessorCompilation>true</MultiProcessorCompilation>\r\n"
"    </ClCompile>\r\n"
"    <ResourceCompile>\r\n"
"      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n"
"      <Culture>0x040b</Culture>\r\n"
"    </ResourceCompile>\r\n"
"    <Lib>\r\n"
"      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>\r\n"
"      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n"
"    </Lib>\r\n"
"    <PostBuildEvent>\r\n"
"      <Command>if not exist ..\\..\\lib mkdir ..\\..\\lib\r\n"
"copy $(OutDir)$(TargetName)$(TargetExt) ..\\..\\lib</Command>\r\n"
"    </PostBuildEvent>\r\n"
"  </ItemDefinitionGroup>\r\n"
"  <ItemDefinitionGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">\r\n"
"    <Midl>\r\n"
"      <TargetEnvironment>X64</TargetEnvironment>\r\n"
"    </Midl>\r\n"
"    <ClCompile>\r\n"
"      <Optimization>Full</Optimization>\r\n"
"      <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>\r\n"
"      <IntrinsicFunctions>true</IntrinsicFunctions>\r\n"
"      <AdditionalIncludeDirectories>..\\..\\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>\r\n"
"      <PreprocessorDefinitions>WIN32;NDEBUG;_LIB;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n"
"      <StringPooling>true</StringPooling>\r\n"
"      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>\r\n"
"      <FunctionLevelLinking>true</FunctionLevelLinking>\r\n"
"      <FloatingPointModel>Fast</FloatingPointModel>\r\n"
"      <PrecompiledHeader />\r\n"
"      <PrecompiledHeaderOutputFile>$(OutDir)$(TargetName).pch</PrecompiledHeaderOutputFile>\r\n"
"      <AssemblerListingLocation>$(OutDir)</AssemblerListingLocation>\r\n"
"      <ObjectFileName>$(OutDir)</ObjectFileName>\r\n"
"      <ProgramDataBaseFileName>$(OutDir)</ProgramDataBaseFileName>\r\n"
"      <WarningLevel>Level3</WarningLevel>\r\n"
"      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n"
"      <DebugInformationFormat />\r\n"
"      <CompileAs>Default</CompileAs>\r\n"
"      <EnableEnhancedInstructionSet>\r\n"
"      </EnableEnhancedInstructionSet>\r\n"
"      <XMLDocumentationFileName>$(IntDir)</XMLDocumentationFileName>\r\n"
"      <BrowseInformationFile>$(IntDir)</BrowseInformationFile>\r\n"
"      <MultiProcessorCompilation>true</MultiProcessorCompilation>\r\n"
"      <LanguageStandard>stdcpp17</LanguageStandard>\r\n"
"    </ClCompile>\r\n"
"    <ResourceCompile>\r\n"
"      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n"
"      <Culture>0x040b</Culture>\r\n"
"    </ResourceCompile>\r\n"
"    <Lib>\r\n"
"      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>\r\n"
"      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n"
"    </Lib>\r\n"
"    <PostBuildEvent>\r\n"
"      <Command>if not exist ..\\..\\lib mkdir ..\\..\\lib\r\n"
"copy $(OutDir)$(TargetName)$(TargetExt) ..\\..\\lib</Command>\r\n"
"    </PostBuildEvent>\r\n"
"  </ItemDefinitionGroup>\r\n"
"  <ItemDefinitionGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">\r\n"
"    <ClCompile>\r\n"
"      <Optimization>Disabled</Optimization>\r\n"
"      <AdditionalIncludeDirectories>..\\..\\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>\r\n"
"      <PreprocessorDefinitions>WIN32;_DEBUG;_LIB;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n"
"      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>\r\n"
"      <FloatingPointModel>Fast</FloatingPointModel>\r\n"
"      <PrecompiledHeader />\r\n"
"      <PrecompiledHeaderOutputFile>$(OutDir)$(TargetName).pch</PrecompiledHeaderOutputFile>\r\n"
"      <AssemblerListingLocation>$(OutDir)</AssemblerListingLocation>\r\n"
"      <ObjectFileName>$(OutDir)</ObjectFileName>\r\n"
"      <ProgramDataBaseFileName>$(OutDir)</ProgramDataBaseFileName>\r\n"
"      <BrowseInformation>true</BrowseInformation>\r\n"
"      <WarningLevel>Level3</WarningLevel>\r\n"
"      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n"
"      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>\r\n"
"      <CompileAs>Default</CompileAs>\r\n"
"      <EnableEnhancedInstructionSet>StreamingSIMDExtensions2</EnableEnhancedInstructionSet>\r\n"
"      <XMLDocumentationFileName>$(IntDir)</XMLDocumentationFileName>\r\n"
"      <BrowseInformationFile>$(IntDir)</BrowseInformationFile>\r\n"
"      <MultiProcessorCompilation>true</MultiProcessorCompilation>\r\n"
"    </ClCompile>\r\n"
"    <ResourceCompile>\r\n"
"      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n"
"      <Culture>0x040b</Culture>\r\n"
"    </ResourceCompile>\r\n"
"    <Lib>\r\n"
"      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>\r\n"
"      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n"
"    </Lib>\r\n"
"    <PostBuildEvent>\r\n"
"      <Command>if not exist ..\\..\\lib mkdir ..\\..\\lib\r\n"
"copy $(OutDir)$(TargetName)$(TargetExt) ..\\..\\lib</Command>\r\n"
"    </PostBuildEvent>\r\n"
"  </ItemDefinitionGroup>\r\n"
"  <ItemDefinitionGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">\r\n"
"    <Midl>\r\n"
"      <TargetEnvironment>X64</TargetEnvironment>\r\n"
"    </Midl>\r\n"
"    <ClCompile>\r\n"
"      <Optimization>Disabled</Optimization>\r\n"
"      <AdditionalIncludeDirectories>..\\..\\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>\r\n"
"      <PreprocessorDefinitions>WIN32;_DEBUG;_LIB;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n"
"      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>\r\n"
"      <FloatingPointModel>Fast</FloatingPointModel>\r\n"
"      <PrecompiledHeader />\r\n"
"      <PrecompiledHeaderOutputFile>$(OutDir)$(TargetName).pch</PrecompiledHeaderOutputFile>\r\n"
"      <AssemblerListingLocation>$(OutDir)</AssemblerListingLocation>\r\n"
"      <ObjectFileName>$(OutDir)</ObjectFileName>\r\n"
"      <ProgramDataBaseFileName>$(OutDir)</ProgramDataBaseFileName>\r\n"
"      <BrowseInformation>true</BrowseInformation>\r\n"
"      <WarningLevel>Level3</WarningLevel>\r\n"
"      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n"
"      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>\r\n"
"      <CompileAs>Default</CompileAs>\r\n"
"      <EnableEnhancedInstructionSet>\r\n"
"      </EnableEnhancedInstructionSet>\r\n"
"      <XMLDocumentationFileName>$(IntDir)</XMLDocumentationFileName>\r\n"
"      <BrowseInformationFile>$(IntDir)</BrowseInformationFile>\r\n"
"      <MultiProcessorCompilation>true</MultiProcessorCompilation>\r\n"
"      <LanguageStandard>stdcpp17</LanguageStandard>\r\n"
"    </ClCompile>\r\n"
"    <ResourceCompile>\r\n"
"      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n"
"      <Culture>0x040b</Culture>\r\n"
"    </ResourceCompile>\r\n"
"    <Lib>\r\n"
"      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>\r\n"
"      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n"
"    </Lib>\r\n"
"    <PostBuildEvent>\r\n"
"      <Command>if not exist ..\\..\\lib mkdir ..\\..\\lib\r\n"
"copy $(OutDir)$(TargetName)$(TargetExt) ..\\..\\lib</Command>\r\n"
"    </PostBuildEvent>\r\n"
"  </ItemDefinitionGroup>\r\n"
"  <ItemGroup>\r\n"
"    <ClCompile Include=\"AAFilter.cpp\">\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">MaxSpeed</Optimization>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">MaxSpeed</Optimization>\r\n"
"    </ClCompile>\r\n"
"    <ClCompile Include=\"BPMDetect.cpp\">\r\n"
"      <DisableSpecificWarnings Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">4996</DisableSpecificWarnings>\r\n"
"      <DisableSpecificWarnings Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">4996</DisableSpecificWarnings>\r\n"
"      <DisableSpecificWarnings Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">4996</DisableSpecificWarnings>\r\n"
"      <DisableSpecificWarnings Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">4996</DisableSpecificWarnings>\r\n"
"    </ClCompile>\r\n"
"    <ClCompile Include=\"cpu_detect_x86.cpp\" />\r\n"
"    <ClCompile Include=\"FIFOSampleBuffer.cpp\">\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">MaxSpeed</Optimization>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">MaxSpeed</Optimization>\r\n"
"    </ClCompile>\r\n"
"    <ClCompile Include=\"FIRFilter.cpp\">\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">MaxSpeed</Optimization>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">MaxSpeed</Optimization>\r\n"
"    </ClCompile>\r\n"
"    <ClCompile Include=\"InterpolateCubic.cpp\" />\r\n"
"    <ClCompile Include=\"InterpolateLinear.cpp\" />\r\n"
"    <ClCompile Include=\"InterpolateShannon.cpp\" />\r\n"
"    <ClCompile Include=\"mmx_optimized.cpp\" />\r\n"
"    <ClCompile Include=\"PeakFinder.cpp\" />\r\n"
"    <ClCompile Include=\"RateTransposer.cpp\">\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">MaxSpeed</Optimization>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">MaxSpeed</Optimization>\r\n"
"    </ClCompile>\r\n"
"    <ClCompile Include=\"SoundTouch.cpp\">\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">MaxSpeed</Optimization>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">MaxSpeed</Optimization>\r\n"
"    </ClCompile>\r\n"
"    <ClCompile Include=\"sse_optimized.cpp\" />\r\n"
"    <ClCompile Include=\"TDStretch.cpp\">\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">Disabled</Optimization>\r\n"
"      <BasicRuntimeChecks Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">EnableFastChecks</BasicRuntimeChecks>\r\n"
"      <BrowseInformation Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">true</BrowseInformation>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">MaxSpeed</Optimization>\r\n"
"      <Optimization Condition=\"'$(Configuration)|$(Platform)'=='Release|x64'\">MaxSpeed</Optimization>\r\n"
"    </ClCompile>\r\n"
"  </ItemGroup>\r\n"
"  <ItemGroup>\r\n"
"    <ClInclude Include=\"..\\..\\include\\BPMDetect.h\" />\r\n"
"    <ClInclude Include=\"..\\..\\include\\FIFOSampleBuffer.h\" />\r\n"
"    <ClInclude Include=\"..\\..\\include\\FIFOSamplePipe.h\" />\r\n"
"    <ClInclude Include=\"..\\..\\include\\SoundTouch.h\" />\r\n"
"    <ClInclude Include=\"..\\..\\include\\STTypes.h\" />\r\n"
"    <ClInclude Include=\"AAFilter.h\" />\r\n"
"    <ClInclude Include=\"cpu_detect.h\" />\r\n"
"    <ClInclude Include=\"FIRFilter.h\" />\r\n"
"    <ClInclude Include=\"InterpolateCubic.h\" />\r\n"
"    <ClInclude Include=\"InterpolateLinear.h\" />\r\n"
"    <ClInclude Include=\"InterpolateShannon.h\" />\r\n"
"    <ClInclude Include=\"PeakFinder.h\" />\r\n"
"    <ClInclude Include=\"RateTransposer.h\" />\r\n"
"    <ClInclude Include=\"TDStretch.h\" />\r\n"
"  </ItemGroup>\r\n"
"  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.targets\" />\r\n"
"  <ImportGroup Label=\"ExtensionTargets\">\r\n"
"  </ImportGroup>\r\n"
"</Project>";

const char* SoundTouch_vcxproj = (const char*) temp_binary_data_2;

//================== soundtouch_config.h.in ==================
static const unsigned char temp_binary_data_3[] =
"/* Use Float as Sample type */\n"
"#undef SOUNDTOUCH_FLOAT_SAMPLES\n"
"\n"
"/* Use Integer as Sample type */\n"
"#undef SOUNDTOUCH_INTEGER_SAMPLES\n"
"\n"
"/* Use ARM NEON extension */\n"
"#undef SOUNDTOUCH_USE_NEON\n";

const char* soundtouch_config_h_in = (const char*) temp_binary_data_3;


const char* getNamedResource (const char* resourceNameUTF8, int& numBytes);
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)
{
    unsigned int hash = 0;

    if (resourceNameUTF8 != nullptr)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0x1a187401:  numBytes = 2798; return Makefile_am;
        case 0x1e03f806:  numBytes = 1422; return SoundTouch_sln;
        case 0x9bb52799:  numBytes = 20439; return SoundTouch_vcxproj;
        case 0x6fff950a:  numBytes = 188; return soundtouch_config_h_in;
        default: break;
    }

    numBytes = 0;
    return nullptr;
}

const char* namedResourceList[] =
{
    "Makefile_am",
    "SoundTouch_sln",
    "SoundTouch_vcxproj",
    "soundtouch_config_h_in"
};

const char* originalFilenames[] =
{
    "Makefile.am",
    "SoundTouch.sln",
    "SoundTouch.vcxproj",
    "soundtouch_config.h.in"
};

const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8);
const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)
{
    for (unsigned int i = 0; i < (sizeof (namedResourceList) / sizeof (namedResourceList[0])); ++i)
        if (strcmp (namedResourceList[i], resourceNameUTF8) == 0)
            return originalFilenames[i];

    return nullptr;
}

}
